### ISSUE TITLE
Claim Fragmentz

### ISSUE THREAD

**Issue by fadhilahmadd** [dante4rt/rivalz-ai-bot#4]
![Screenshot 2024-11-17 at 16 34 20](https://github.com/user-attachments/assets/95996104-5d62-4c56-b57e-7da6f6fbb394)
Claim fragmentz yg Type 12 hours reccuring claim, setelah selesai cronjob gajalan
Error :
/root/rivalz-ai-bot/index.js:210
      if (action === '1' && claimOption === '2') {
                            ^

ReferenceError: claimOption is not defined
    at main (/root/rivalz-ai-bot/index.js:210:29)

Node.js v22.11.0

**Comment by fadhilahmadd** [comment]
barangkali membantu, tambah let claimOption; pada fungsi main()

async function main() {
  displayHeader();

  const provider = new JsonRpcProvider(RPC_URL);

  let claimOption;

 .... dst
}
![Screenshot 2024-11-17 at 16 34 56](https://github.com/user-attachments/assets/3431235b-5aa2-40f4-983c-9e63716c1ed8)
Work😁

**Comment by dante4rt** [comment]
> ![Screenshot 2024-11-17 at 16 34 20](https://private-user-images.githubusercontent.com/62607308/386938779-95996104-5d62-4c56-b57e-7da6f6fbb394.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MzcyOTgsIm5iZiI6MTczMTgzNjk5OCwicGF0aCI6Ii82MjYwNzMwOC8zODY5Mzg3NzktOTU5OTYxMDQtNWQ2Mi00YzU2LWI1N2UtN2RhNmY2ZmJiMzk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA5NDk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzZmMwMDZmOWEyNjNjMWQxMGU5ZGU3ZTU4OWFhMDMyN2YxNjBlOWVlMzMwODdmMDk5MDUyZGVmODM5MWE4NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JIHVjmHStA1-oBcDaKVSXHEi5-AOK-WCYG7qolEn1Es) Claim fragmentz yg Type 12 hours reccuring claim, setelah selesai cronjob gajalan Error : /root/rivalz-ai-bot/index.js:210 if (action === '1' && claimOption === '2') { ^
> 
> ReferenceError: claimOption is not defined at main (/root/rivalz-ai-bot/index.js:210:29)
> 
> Node.js v22.11.0

Fixed here:
https://github.com/dante4rt/rivalz-ai-bot/commit/8dfd7b991283b7a23369f721aeb209aebe16183e

Thank you!
